FROM powerapi/powerapi:pypy-1.0.0
USER powerapi
COPY --chown=powerapi . /tmp/virtualwatts

RUN cd /tmp/virtualwatts && \
	wget https://raw.githubusercontent.com/powerapi-ng/powerapi-ci-env/main/to_36.sh && \
	/bin/bash to_36.sh virtualwatts

RUN pypy3 -m pip install --user --no-cache-dir "/tmp/virtualwatts" && rm -r /tmp/virtualwatts

ENTRYPOINT ["pypy3", "-m", "virtualwatts"]
