FROM powerapi/powerapi:pypy-1.0.0
USER powerapi
COPY --chown=powerapi . /tmp/virtualwatts

RUN cd /tmp/virtualwatts && \
    sed -i 's/ *-> *[[:alnum:]]*Report//g' $(find virtualwatts/ -name "*.py") && \
    sed -i 's/from __future__ import annotations//g' $(find virtualwatts/ -name "*.py") && \
    sed -i 's/python_requires = >= 3\.[0-9]/python_requires = >= 3.6/g' setup.cfg


RUN pypy3 -m pip install --user --no-cache-dir "/tmp/virtualwatts" && rm -r /tmp/virtualwatts

ENTRYPOINT ["pypy3", "-m", "virtualwatts"]
